version: 3

silent: true

dotenv: 
  - .env

includes:
  kube:
    taskfile: ./taskfiles/Kube.yaml
  helm:
    taskfile: ./taskfiles/Helm.yaml

tasks:
  version:
    desc: Current version of tb
    cmds:
      - echo "0.1.0"

