version: 3

silent: true

env:
  # disable jq coloring
  NO_COLOR: true

dotenv: 
  - .env

includes:
  kube:
    taskfile: ./taskfiles/Kube.yaml
    aliases: [k]

tasks:
  version:
    desc: Current version of tb
    cmds:
      - echo "0.1.0"

