#!/bin/bash
set -o allexport

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
TB_FILE="$(pwd)/.tb"

if [ -f "$TB_FILE" ]; then
  source $TB_FILE
fi

task -t $SCRIPT_DIR/Taskfile.yaml $@
